### ISSUE TITLE
Cannot import name 'TriMesh' from matplotlib.tri

### ISSUE THREAD

**Issue by marybj-ocwcog** [raphaelquast/EOmaps#163] opened 2023-04-24 21:51 UTC
Receive a warning when importing Maps from eomaps:  Cannot import name 'TriMesh' from matplotlib.tri.

**Comment by raphaelquast** [comment] 2023-04-25 07:42
Hey, sorry to hear that!

This is most probably caused by the fact that you use an outdated `EOmaps` version (<4.4) together with a new `matplotlib` version (>3.5)

- Can you confirm that you use the most recent EOmaps version (v6.4) ?

If updating EOmaps does not help, please provide some additional details on your environment so that we can pinpoint the problem.  (e.g. if you use `conda` or `mamba`, please provide the output of `conda list` (or `mamba list`))

**Comment by marybj-ocwcog** [comment] 2023-04-25 16:31
Hello,
I updated my environment and have attached the list - eomaps appears to be version 3.0, and matplotlib appears to be 3.7.1.  I recently uninstalled Anaconda and replaced it with Mamba so my current environment - mymainenv - is freshly installed as of about two weeks ago.  I am still quite new to this, so I very much appreciate your help!

I only found Eomaps yesterday and installed it, but I am very excited that it will help me create the visualizations I need.
Thank you!
Mary Bach-Jackson



[Logo, company name  Description automatically generated with medium confidence]
Mary Bach-Jackson (she/her)
GIS Analyst

Oregon Cascades West Council of Governments (OCWCOG)
1400 Queen Ave SE, Suite 201
Albany, OR 97322
Ph: 541-924-8426
www.ocwcog.org<https://www.ocwcog.org/#content>

**Comment by raphaelquast** [comment] 2023-04-25 17:40
Hey, great to hear that you give EOmaps a try!

Ok, so my initial guess was right... you've got a quite outdated EOmaps version (current=`v6.4`, your version=`v3.0`) which is apparently no longer compatible with the latest matplotlib-version.

You can tell mamba to install the latest EOmaps version with the following command:

 `mamba install -c conda-forge eomaps=6.4`

This should update eomaps and get rid of the error.


If it doesn't work, maybe have a look at the [🚀 From 0 to EOmaps - a quickstart guide](https://eomaps.readthedocs.io/en/dev/FAQ.html#from-0-to-eomaps-a-quickstart-guide) from the docs!

**Comment by raphaelquast** [comment] 2023-05-19 22:13
I'm closing this since it is not really an issue with EOmaps... feel free to re-open if you need more help!

**Closed by raphaelquast** 2023-05-19 22:13 UTC
Labels: installation / ext. packages, awaiting followup
